---
- ak-demo:
    repositories:
    - url:
      pipeline_name:
      pipeline_config_path: 
      pipeline_vars_path: 
- ak-docker-demo:
    - url:
      pipeline_name:
      pipeline_config_path: 
      pipeline_vars_path: 
- ak-learning:
    repositories:
    - url: https://bitbucket.org/armakuni/ak-learning/
      pipeline_name: ak-learning
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: 
    - url: https://bitbucket.org/armakuni/ak-toolbox
      pipeline_name: ak-toolbox
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
    - url: https://bitbucket.org/armakuni/k8sappdeploy/
      pipeline_name: k8sappdeploy
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
    - url: https://bitbucket.org/armakuni/raindrops-le/
      pipeline_name: raindrops-le
      pipeline_config_path: $REPO/ci/pipeline.yaml
      pipeline_vars_path: ''
    - url: <NOT_FOUND>
      pipeline_name: raindrop-am
      pipeline_config_path: 
      pipeline_vars_path: ''
    - url: https://bitbucket.org/armakuni/savage-bot/
      pipeline_name: savage-bot
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
    - url: https://bitbucket.org/armakuni/dazforms/
      pipeline_name: dazforms
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
    - url: https://github.com/armakuni/fizzbuzzfeed
      pipeline_name: as-fizzbuzzfeed
      pipeline_config_path: $REPO/pipeline.yml
      pipeline_vars_path: ''
    - url: https://github.com/armakuni/buzzfizzfeed
      pipeline_name: as-buzzfizzfeed
      pipeline_config_path: $REPO/pipeline.yml
      pipeline_vars_path: ''
- ak-software-github:
    repositories:
    - url: <NOT_FOUND>
      pipeline_name: ak-adoption-training-presentation-generate
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
    - url: https://bitbucket.org/armakuni/tech-radar-alerter/
      pipeline_name: ak-tech-radar-alerter
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
- akstats:
    repositories:
    - url: https://bitbucket.org/armakuni/ak-stats/
      pipeline_name: ak-stats
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
- cfdemo:
    repositories:
    - url:
      pipeline_name:
      pipeline_config_path: 
      pipeline_vars_path: 
- engagementcsv:
    repositories:
    - url: https://bitbucket.org/armakuni/engagementcsv
      pipeline_name: engagementcsv
      pipeline_config_path: $REPO/pipeline.yml
      pipeline_vars_path: ''
- ocr-postits:
    repositories:
    - url: https://bitbucket.org/armakuni/ocr-postits
      pipeline_name: ocr-postits
      pipeline_config_path: $REPO/pipeline.yml
      pipeline_vars_path: ''
- ons-k8s-sandbox:
    repositories:
    - url: https://bitbucket.org/armakuni/ons-k8s-sandbox/
      pipeline_name: infrastructure
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
    - url: https://bitbucket.org/armakuni/ons-k8s-sandbox/
      pipeline_name: infrastructure-destroy
      pipeline_config_path: $REPO/ci/pipeline.destroy.yml
      pipeline_vars_path: ''
- radar:
    repositories:
    - url: https://bitbucket.org/armakuni/build-your-own-radar/
      pipeline_name: radar
      pipeline_config_path: $REPO/pipeline.yml
      pipeline_vars_path: ''
- rbs-devops-capability:
    repositories:
    - url: https://bitbucket.org/armakuni/devops_techtree_prettifier
      pipeline_name: rbs-devops-capability
      pipeline_config_path: $REPO/ci/pipeline.yaml
      pipeline_vars_path: ''
- theway:
    repositories:
    - url: https://bitbucket.org/armakuni/ak-way-v2/
      pipeline_name: the-way
      pipeline_config_path: $REPO/pipeline.yml
      pipeline_vars_path: ''
- vsm:
    repositories: 
    - url: https://bitbucket.org/armakuni/value-stream-mapping-ui/
      pipeline_name: vsm
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
- flex50:
    repositories:
    - url: https://bitbucket.org/armakuni/rrw-tp-api-service-lambda
      pipeline_name: rrw
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''
    - url: <NOT_FOUND>
      pipeline_name: rrw-fedex-parser
      pipeline_config_path: pipeline.yml
      pipeline_vars_path: ''
    - url: <NOT_FOUND>
      pipeline_name: harvester
      pipeline_config_path: pipeline.yml
      pipeline_vars_path: ''
- main:
    repositories:
    - url: https://bitbucket.org/armakuni/cubinote-webhook/
      pipeline_name: ak-cubinote-webhook
      pipeline_config_path: $REPO/ci/pipeline.yml
      pipeline_vars_path: ''


